#!/bin/tcsh -f
# unix install script

echo compiling libmini...
(cd mini; cmake . && make)
echo compiling libvolren...
cmake . && make
echo compiling qtv3...
(cd qtv3; cmake . && make)
echo installing qtv3...
echo enter root password when prompted
(cd qtv3; sudo make install)
